Fix StorageTransactionError
Do not store neither the utility in local variables nor the annotations. This
prevents the following error:

StorageTransactionError: Duplicate tpc_begin calls for same transaction

This error is rised because of a deadlock when same transaction opens
multiple connections to same storage. Further information:
https://github.com/zopefoundation/ZODB/issues/258