Refactor to not rely on annotations (#8)
* APi endpoints and removal of annotations requirement

* Remove obsolete views

* Clarifying comments

* Reorganize viewlets and views

* Remove unused viewlet

* Imports cleanup

* Move static resources into browser package

* Rename module pas to pasplugin

* Beautify mixin

* Remove unused function from api module

* Beautify and changelog

* Added dependency: senaite.jsonapi

* Clean-up queue's control panel (remove confusing settings)

* Support for off-line mode (when queue server is offline or not reachable)

* Remove missed call

* Clean-up

* Typos and fix consumer_id

* noqas

* Support for multiple consumers

* Make new attempts to increase ceil(max_seconds * 1.5)

* Keep headless queue utility in sync

* Better handling of headless fallback

* Better handling of headless mode

* Push mechanism for add/done operations performed off-line

* Move QueueAuth inside pasplugin module

* Fix the retrieval of current zeo's url

* Cleanup, removal of mixin

* is_queue_writable -> is_queue_ready

* is_queue_readable -> is_queue_enabled

* Cleanup and renaming of utilities

* Added viewlet for queue server status

* Missing functions in interfaces

* Add Queue monitor view using core's listing format

* Missed to add the view and the template

* Clean-up consumer

* Consumer fixtures

* Fix traceback when assigning a Worksheet Template without analyses

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.worksheet.views.add_analyses, line 130, in __call__
  Module senaite.queue.monkeys.browser.worksheet, line 41, in handle_submit
  Module bika.lims.content.worksheet, line 1074, in applyWorksheetTemplate
  Module senaite.queue.monkeys.content.worksheet, line 124, in
_apply_worksheet_template_routine_analyses
ValueError: need more than 0 values to unpac

* Increase default object per task from 5 to 10

* Add server_status_cache_key to Server queue offline viewlet

* Added requeue and remove action buttons in Tasks listing view

* Display failed tasks in tasks monitor view

* Some analyses that are displayed as unassigned are not (to be fixed in core)

* Allow the creation of tasks without the need of context

* Allow to pass the auth key to QueueAuth directly

* Support for "ghost" tasks (clients are not notified about them)

* Make the consumer to work in a new thread to not flood worker

* Slightly better sync of clients with server (still work to do)

* Add filter for "Failed" tasks in queue monitoring view

* Add diff endpoint and better sync process of client with server

* Better handling of get calls in server's queue

* Safe assignment of analyses in worksheet

* Keep analyses sorted by sample id when a worksheet template is used

* Small bits

* Make get_tasks_for to return a list instead of an iterator

* Increse sync frequency when queue server not reachable

* Delay parameter to prevent tasks to start while request has not finished

* Failed tasks are immediately marked as done afterwards

* Better handling of HTTP error status codes

* Display pagination and some styling in tasks view

* Display Queued tasks instead of Active tasks in filter

* Display "ghost" next to status for ghost tasks

* Update installation instructions

* Update QuickStart documentation

* Update Handling documentation

* Update extend documentation

* Update installation documentation

* Better handling of tasks that timeout

* Make consumer notify server about timed-out tasks

* Typos and cleanup

* Add requeue and remove buttons for "All tasks" listing

* Do not allow the assignment of a WST when Worksheet is queued

* Reduce the chunk_size half on failing tasks

* Extend arithmetic operation to float w/o modification

* Renaming of filter buttons

* Reindex worksheet after analyses are assigned

* Take only 3d level into account when poping tasks

* Keep natural order in samples when Worksheet Template is used

* Doctests revisit and fixes

* Simplify get_chunks_for

* Update release notes