Fix traceback on reindex object security
Queue task for the reindex of object security indexes keep failing
because of no ceiling when walking up to find nodes:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.contact, line 62, in __call__
  Module bika.lims.browser.contact, line 186, in _link_user
  Module bika.lims.content.contact, line 143, in setUser
  [...]
  Module senaite.queue.api, line 294, in add_reindex_obj_security_task
  Module senaite.queue.api, line 274, in walk_up
  Module senaite.queue.api, line 274, in walk_up
  Module senaite.queue.api, line 270, in walk_up
  Module senaite.queue.api, line 245, in walk_down
  Module bika.lims.api, line 429, in get_uid
  Module bika.lims.api, line 239, in get_object
  Module bika.lims.api, line 202, in fail
APIError: <AuditLogCatalog at /senaite/auditlog_catalog> is not supported.
```